name: Update Grype

on: 
  schedule:
  - cron: 0 13 * * 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update Grype
        run: tools/bazel run //:update-grype
      - name: Rerun CVE Scans
        run: tools/bazel test //...
      - name: Commit updated database
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'main'
          commit-message: 'Update Grype Database'
          force-add: 'true'
          files: WORKSPACE
          name: Github Actions
          email: github-actions@psanders.me
